import * as THREE from './vendor/three.module.js';
import {RaceAudio} from './audio.js';
import {setup,applyAction,validateAction} from './race-rules.js';
const $=id=>document.getElementById(id), game=$('game'), canvas=$('world');
const audio=new RaceAudio({onStatus:syncAudioUI});
function syncAudioUI(status){const button=$('sound');if(!button)return;const muted=audio.settings.muted;button.setAttribute('aria-pressed',String(muted));button.setAttribute('aria-label',muted?'Unmute audio':'Mute audio');button.title=muted?'Unmute audio (M)':'Mute audio (M)';button.classList.toggle('muted',muted);$('audioStatus').textContent=!status.supported?'Audio unavailable in this browser':status.failures.length?'Some audio could not load; racing is unaffected':status.ready?'Jungle soundtrack + adaptive river audio':'Sound starts when you race';}
const playerId='you'; let state=setup([playerId]),renderer,scene,camera,clock=0,acc=0,last=0,steer=0,keys={},queued=[],counting=false,reduced=false,hq=true;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const center=z=>Math.sin(z*.0065)*12+Math.sin(z*.017)*3;
function level(z,x=0){let y=-z*.011;for(const f of state.forks)if(z>f.start+95&&z<f.start+200&&x<-6)y-=Math.sin((z-f.start-95)/105*Math.PI)*3.4;return y;}
const point=(x,y,z)=>new THREE.Vector3(center(z)+x,level(z,x)+y,-z);
const seed=n=>{let x=Math.sin(n*127.1+311.7)*43758.5453123;return x-Math.floor(x);};
const colors={rock:0x7c8370,leaf:0x38854a,bark:0x645346,lime:0xc3f542,water:0x26aeb6};
const mats={},obstacleViews=[],falls=[],rivals=[],rings=[],decor=[],terrainBatches=[],dummy=new THREE.Object3D(),look=new THREE.Vector3(),camTarget=new THREE.Vector3();
let disc,water,waterMat,particles,particleGeo,particleData=[],particlePositions,particleColors,particleCursor=0,sceneReady=false,eventSeen=0,feedbackUntil=0,boostFlash=0,frameCounter=0,fps=60,frameSample=0,cpuMs=0,startedAt=0;
const racerNames=['SkyThrower','RiverRider','DiscNomad','LeafyLoop','AeroAsh','SpinDoctor','WaveRider'];
const racerColors=[0x5ccaff,0xff755e,0xf3ba61,0xb4d17c,0xb193ed,0x5accc0,0xf0acc0];
const racerRates=[46.8,45.3,42.5,41.8,41,40,39];
const racerOffsets=[10,5,-6,-12,-18,-23,-29];
let rank=3;
function material(color,roughness=.85,metalness=0){return new THREE.MeshStandardMaterial({color,roughness,metalness});}
function instanced(geometry,mat,transforms){const chunks=new Map();for(const t of transforms){const k=Math.floor(-t.p[2]/180);if(!chunks.has(k))chunks.set(k,[]);chunks.get(k).push(t);}for(const [k,items] of chunks){const mesh=new THREE.InstancedMesh(geometry,mat,items.length);items.forEach((t,i)=>{dummy.position.set(...t.p);dummy.rotation.set(...(t.r||[0,0,0]));dummy.scale.set(...(t.s||[1,1,1]));dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);if(t.c)mesh.setColorAt(i,new THREE.Color(t.c));});mesh.computeBoundingSphere();scene.add(mesh);terrainBatches.push({mesh,z:k*180});}}
function combineStatic(group){const byMaterial=new Map();for(const child of [...group.children]){if(!child.isMesh)continue;const key=child.material;if(!byMaterial.has(key))byMaterial.set(key,[]);byMaterial.get(key).push(child);}for(const [mat,meshes] of byMaterial){if(meshes.length<2)continue;const p=[],n=[],uv=[];for(const m of meshes){m.updateMatrix();const g=m.geometry.index?m.geometry.toNonIndexed():m.geometry.clone();g.applyMatrix4(m.matrix);p.push(...g.attributes.position.array);n.push(...g.attributes.normal.array);if(g.attributes.uv)uv.push(...g.attributes.uv.array);group.remove(m);g.dispose();}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(n,3));if(uv.length)g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));group.add(new THREE.Mesh(g,mat));}}
function rockGeometry(){const g=new THREE.IcosahedronGeometry(1,2);const a=g.attributes.position;for(let i=0;i<a.count;i++){const x=a.getX(i),y=a.getY(i),z=a.getZ(i),s=1+.13*Math.sin(x*11+y*7+z*13)+.07*Math.sin(y*23-z*8);a.setXYZ(i,x*s,y*s,z*s);}g.computeVertexNormals();return g;}
function leafGeometry(){const p=[],uv=[];for(let i=0;i<10;i++){const a=i/10,b=(i+1)/10;for(const [t,side] of [[a,-1],[a,1],[b,-1],[a,1],[b,1],[b,-1]]){const width=Math.sin(t*Math.PI)*.23; p.push(t*4,Math.sin(t*Math.PI)*.7-t*t*.7,width*side);uv.push(t,(side+1)/2);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.computeVertexNormals();return g;}
function buildEnvironment(){
 const rockGeo=rockGeometry(),rockT=[],cliffT=[],trunkT=[],leafT=[],canopyT=[],shoreT=[];
 mats.rock=material(colors.rock,.96);mats.cliff=material(0x9c9b80,.95);mats.bark=material(colors.bark,.94);mats.leaf=material(0x467e36,.78);mats.leaf.side=THREE.DoubleSide;mats.canopy=material(0x286846,1);
 const loader=new THREE.TextureLoader();loader.load('/assets/limestone.jpg',texture=>{texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(1.5,1.5);texture.anisotropy=4;mats.rock.map=texture;mats.rock.needsUpdate=true;mats.cliff.map=texture;mats.cliff.needsUpdate=true;},undefined,()=>{});
 for(let i=0;i<420;i++){
  const z=-70+i*6.4;for(const side of [-1,1]){
   const a=i*7+(side+1),x=side*(21+seed(a)*9),h=2+seed(a+5)*6,wp=point(x,h*.35,z);
   rockT.push({p:wp.toArray(),s:[3+seed(a+1)*5,h,3+seed(a+2)*6],r:[seed(a+3)*.7,seed(a+4)*6,.15],c:new THREE.Color().setHSL(.17,.13,.34+seed(a+2)*.14)});
   if(i%2===0){const tx=side*(24+seed(a+14)*12),height=9+seed(a+6)*9,base=point(tx,2,z);trunkT.push({p:[base.x,base.y+height*.5,base.z],s:[.45,height,.45],r:[side*.09,seed(a)*6,side*.15]});
    for(let j=0;j<8;j++)leafT.push({p:[base.x-side*height*.12,base.y+height,base.z],s:[1.15+seed(a+j)*.65,1,1.2],r:[.15+seed(a+j)*.3,j*Math.PI/4+seed(a)*2,seed(a+j)*.25-.15],c:new THREE.Color().setHSL(.23+seed(a+j)*.08,.42,.21+seed(a+8+j)*.13)});
    canopyT.push({p:point(side*(32+seed(a+2)*13),height*.65,z+4).toArray(),s:[4+seed(a)*5,3+seed(a+1)*5,5+seed(a+6)*4],c:new THREE.Color().setHSL(.27,.35,.17+seed(a)*.12)});
   }
   if(i%5===0){const h=24+seed(a+11)*39;cliffT.push({p:point(side*(36+seed(a+22)*11),h*.37-3,z).toArray(),s:[12+seed(a+31)*8,h*.65,15+seed(a+4)*11],r:[.1,seed(a+2)*6,side*.12]});canopyT.push({p:point(side*36,h*.9,z).toArray(),s:[12,4,16]});}
  }
 }
 // The islands physically separate three channels; all placements are fixed.
 for(const f of state.forks)for(let z=f.start+20;z<f.end-20;z+=8)for(const x of [-6,6]){rockT.push({p:point(x,1.4,z).toArray(),s:[1.35,2.5+seed(z)*2,5.5],r:[.1,seed(z)*2,.1]});if(z%3<1)canopyT.push({p:point(x,4,z).toArray(),s:[1.8,1.5,4]});}
 instanced(rockGeo,mats.rock,rockT);instanced(rockGeo,mats.cliff,cliffT);instanced(new THREE.CylinderGeometry(.65,1,1,7),mats.bark,trunkT);instanced(leafGeometry(),mats.leaf,leafT);instanced(new THREE.IcosahedronGeometry(1,2),mats.canopy,canopyT);
 // Towering distant monoliths and sunlit ridgelines.
 const mountains=[];for(let i=0;i<28;i++){const z=i*100+140;mountains.push({p:point((i%2?1:-1)*(65+seed(i)*40),40,z).toArray(),s:[27,65+seed(i+11)*60,34],r:[.1,i*.8,0]});}instanced(rockGeo,material(0x668b85),mountains);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(600,3200),material(0x385d44));ground.rotation.x=-Math.PI/2;ground.position.set(0,-35,-1300);scene.add(ground);
 // Falls flank the race in addition to the risky left-hand drop.
 const fallMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:{time:{value:0}},vertexShader:'varying vec2 vUv; void main(){vUv=uv; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv; uniform float time; void main(){float streak=sin(vUv.x*140.+sin(vUv.x*45.)*2.)*.5+.5; float rush=sin(vUv.y*80.+time*11.+vUv.x*24.)*.5+.5;float a=smoothstep(0.,.12,vUv.x)*smoothstep(1.,.87,vUv.x);gl_FragColor=vec4(mix(vec3(.23,.65,.68),vec3(.91,1.,.96),.4+streak*.45+ rush*.15),a*.77);}' });
 mats.fall=fallMat;
 for(let i=0;i<30;i++){const z=80+i*88,side=i%2?1:-1,h=23+seed(i)*27;const m=new THREE.Mesh(new THREE.PlaneGeometry(5+seed(i+1)*6,h,1,1),fallMat);m.position.copy(point(side*25,h*.5+1,z));m.rotation.y=side*.6;scene.add(m);falls.push({mesh:m,z});}
 // Cave roofs: open-ended rock arches, not dark rectangles.
 const caveT=[];for(const f of state.forks)for(let z=f.start+40;z<f.end-30;z+=17)for(let j=0;j<9;j++){const a=j/8*Math.PI;caveT.push({p:point(12+Math.cos(a)*5.8,Math.sin(a)*7.5+1.1,z).toArray(),s:[1.7,2.4,10],r:[0,.2,a]});}instanced(rockGeo,mats.rock,caveT);
 // Animated overhead lianas and hanging foliage.
 const vineMat=material(0x4b6435);const vineTransforms=[];for(let i=0;i<55;i++){const z=70+i*42;const side=i%2?1:-1;vineTransforms.push({p:point(side*19,8,z).toArray(),s:[.12,12+seed(i)*8,.12],r:[0,0,side*.1]});}instanced(new THREE.CylinderGeometry(1,1,1,5),vineMat,vineTransforms);
 buildWater();buildObstacles();buildFinish();
}
function buildWater(){
 const pos=[],uv=[],idx=[];const nx=32,nz=1000;for(let iz=0;iz<=nz;iz++){const z=-70+iz*2.6;for(let ix=0;ix<=nx;ix++){const x=-27+ix/nx*54;pos.push(center(z)+x,level(z,x),-z);uv.push(x,z);}}
 for(let iz=0;iz<nz;iz++)for(let ix=0;ix<nx;ix++){const a=iz*(nx+1)+ix,b=a+nx+1;idx.push(a,b,a+1,b,b+1,a+1);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();
 waterMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:{time:{value:0},player:{value:new THREE.Vector3()},dive:{value:0},speed:{value:0},fogColor:{value:new THREE.Color(0xafd4d5)}},vertexShader:`varying vec2 vUv;varying vec3 vWorld;varying float vDepth;uniform float time;void main(){vUv=uv;vec3 p=position;p.y+=sin(uv.x*1.5+uv.y*.65+time*4.)*.12+sin(uv.y*1.4+time*6.+uv.x*.7)*.065;vWorld=p;vec4 mv=modelViewMatrix*vec4(p,1.);vDepth=-mv.z;gl_Position=projectionMatrix*mv;}`,
 fragmentShader:`varying vec2 vUv;varying vec3 vWorld;varying float vDepth;uniform float time;uniform vec3 player;uniform float dive;uniform float speed;uniform vec3 fogColor;
 float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}
 void main(){vec2 p=vec2(vUv.x,vUv.y+time*15.);float n=noise(p*.55)+.5*noise(p*1.7);float wave=sin(p.y*2.4+sin(p.x*2.1+n*4.)*1.6);float foam=smoothstep(.82,1.,wave)*smoothstep(.83,1.37,n);float fleck=pow(max(0.,sin(p.x*4.+n*6.)*sin(p.y*6.)),14.);vec3 c=mix(vec3(.017,.25,.29),vec3(.065,.66,.67),clamp(n*.73,0.,1.));c=mix(c,vec3(.73,.94,.87),foam*.78+fleck*.3);float bank=smoothstep(17.5,23.,abs(vUv.x));c=mix(c,vec3(.46,.81,.73),bank*smoothstep(.9,1.3,n)*.55);
 vec2 rel=vec2(vWorld.x-player.x,vWorld.z-player.z);float trail=smoothstep(0.,1.,rel.y)*(1.-smoothstep(3.,21.,rel.y));float edge=abs(abs(rel.x)-(.45+rel.y*.23));float wake=(1.-smoothstep(.0,.48,edge))*trail;float churn=(1.-smoothstep(.2,1.4,abs(rel.x)))*trail*noise(p*4.);c=mix(c,vec3(.85,1.,.95),clamp((wake*.8+churn*.6)*(1.-dive),0.,.94));
 vec3 norm=normalize(vec3(cos(p.x*1.5+p.y*.65)*.18,1.,cos(p.y*1.4+p.x*.7)*.15));vec3 view=normalize(cameraPosition-vWorld);float spec=pow(max(0.,dot(reflect(-normalize(vec3(-.4,.7,-.25)),norm),view)),100.);c+=vec3(1.,.91,.64)*spec*.85;float fog=1.-exp(-vDepth*vDepth*.000009);c=mix(c,fogColor,fog);gl_FragColor=vec4(c,mix(.97,.22,dive));}`});
 water=new THREE.Mesh(g,waterMat);water.renderOrder=1;scene.add(water);
}
function discTexture(){const c=document.createElement('canvas');c.width=c.height=512;const a=c.getContext('2d');a.fillStyle='#111d27';a.fillRect(0,0,512,512);a.translate(256,256);for(let i=0;i<32;i++){a.save();a.rotate(i*Math.PI/16);a.strokeStyle=i%2?'#dce9e4':'#789b9f';a.lineWidth=i%2?5:2;a.beginPath();a.moveTo(90,0);a.bezierCurveTo(145,-75,205,20,232,0);a.bezierCurveTo(195,60,143,19,112,70);a.stroke();a.restore();}a.strokeStyle='#d2f943';a.lineWidth=5;a.beginPath();a.moveTo(-55,-26);a.lineTo(-42,30);a.lineTo(43,30);a.lineTo(57,-26);a.lineTo(25,-3);a.lineTo(0,-41);a.lineTo(-25,-3);a.closePath();a.stroke();a.beginPath();a.moveTo(-40,42);a.lineTo(42,42);a.stroke();a.strokeStyle='#e0e9df';a.lineWidth=2;a.beginPath();a.arc(0,0,243,0,Math.PI*2);a.stroke();const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;return texture;}
const discMap=discTexture();
function makeDisc(color,hero=false){const group=new THREE.Group();const p=[new THREE.Vector2(0,.02),new THREE.Vector2(.65,.04),new THREE.Vector2(1.03,.02),new THREE.Vector2(1.16,.08),new THREE.Vector2(1.2,.2),new THREE.Vector2(1.17,.27),new THREE.Vector2(1,.32),new THREE.Vector2(.65,.36),new THREE.Vector2(0,.36)];const body=new THREE.Mesh(new THREE.LatheGeometry(p,64),material(0x17212b,.22,.82));group.add(body);const face=new THREE.Mesh(new THREE.CircleGeometry(1.09,64),new THREE.MeshStandardMaterial({map:discMap,roughness:.38,metalness:.15}));face.rotation.x=-Math.PI/2;face.position.y=.375;group.add(face);const rim=new THREE.Mesh(new THREE.TorusGeometry(1.16,.035,8,64),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:hero?2:.85,roughness:.2,metalness:.5}));rim.rotation.x=Math.PI/2;rim.position.y=.11;group.add(rim);if(hero){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.19,.022,6,64),material(0xf1f5e7,.15,.95));ring.rotation.x=Math.PI/2;ring.position.y=.26;group.add(ring);}scene.add(group);return group;}
function mesh(geo,mat,group,x=0,y=0,z=0){const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);group.add(m);return m;}
function buildObstacles(){
 mats.log=material(0x6a4630,.9);mats.cut=material(0xb99a68);mats.vine=material(0x76a33b,.9);mats.gold=new THREE.MeshStandardMaterial({color:0xffcb66,emissive:0xffae32,emissiveIntensity:2,metalness:.4,roughness:.2});
 for(const o of state.obstacles){const g=new THREE.Group();g.position.copy(point(o.x,0,o.z));scene.add(g);let visual;
  if(o.type==='rock'||o.type==='underrock'){visual=mesh(rockGeometry(),mats.rock,g);visual.scale.set(o.w, o.type==='rock'?2.1:1.7,2.1);visual.position.y=o.type==='rock'?.25:-2.4;visual.rotation.set(.3,o.z,.2);}
  if(o.type==='log'){visual=mesh(new THREE.CylinderGeometry(.48,.62,o.w*2,12),mats.log,g);visual.rotation.z=Math.PI/2;visual.position.y=.48;for(const x of [-o.w,o.w]){const cut=mesh(new THREE.CircleGeometry(.45,16),mats.cut,g,x,.48,0);cut.rotation.y=x>0?Math.PI/2:-Math.PI/2;}const twig=mesh(new THREE.CylinderGeometry(.13,.24,2.5,7),mats.log,g,1,1,0);twig.rotation.z=-.8;}
  if(o.type==='bridge'){const b=mesh(new THREE.BoxGeometry(o.w*2+2,.7,4.8),mats.log,g,0,.6,0);for(const x of [-o.w,o.w]){mesh(new THREE.CylinderGeometry(.38,.6,5,7),mats.log,g,x,1,0);mesh(new THREE.BoxGeometry(.2,1.3,5),mats.log,g,x,1.6,0);}for(let i=-o.w;i<o.w;i+=1.3)mesh(new THREE.BoxGeometry(.14,.15,4.8),mats.cut,g,i,1.02,0);}
  if(o.type==='vine'){for(let i=-o.w;i<=o.w;i+=1.1){const v=mesh(new THREE.CylinderGeometry(.11,.17,7,6),mats.vine,g,i,2.6,0);v.rotation.z=Math.sin(i)*.12;}mesh(new THREE.CylinderGeometry(.18,.18,o.w*2+1,6),mats.log,g,0,4.6,0).rotation.z=Math.PI/2;}
  if(o.type==='ring'){visual=mesh(new THREE.TorusGeometry(2.1,.11,8,48),mats.gold,g,0,2.35,0);mesh(new THREE.TorusGeometry(2.3,.035,6,48),mats.gold,g,0,2.35,0);rings.push({mesh:g,z:o.z});}
  if(o.type==='whirl'){visual=mesh(new THREE.CircleGeometry(o.w,48),new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:{time:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv*2.-1.;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv;uniform float time;void main(){float r=length(vUv);float a=atan(vUv.y,vUv.x);float s=sin(a*4.+r*24.-time*6.)*.5+.5;vec3 c=mix(vec3(.0,.10,.14),vec3(.4,.83,.78),s*r);gl_FragColor=vec4(c,smoothstep(1.,.7,r)*.9);}' }),g,0,.23,0);visual.rotation.x=-Math.PI/2;visual.renderOrder=2;}
  if(o.type==='drop'){visual=mesh(new THREE.PlaneGeometry(9,5),mats.fall,g,0,-1.5,0);}
  if(o.type!=='whirl')combineStatic(g);
  obstacleViews.push({o,g,visual});
 }
}
function buildFinish(){const g=new THREE.Group();g.position.copy(point(0,0,2400));scene.add(g);const pillar=material(0x334e40);for(const x of [-19,19])mesh(new THREE.CylinderGeometry(.6,1,15,10),pillar,g,x,6,0);const c=document.createElement('canvas');c.width=1024;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#102621';ctx.fillRect(0,0,1024,128);for(let x=0;x<1024;x+=32)for(let y=0;y<128;y+=32)if((x/32+y/32)%2===0){ctx.fillStyle='#d3e9d7';ctx.fillRect(x,y,32,32);}ctx.fillStyle='#0b241d';ctx.fillRect(295,0,434,128);ctx.fillStyle='#c3f542';ctx.font='bold 80px sans-serif';ctx.textAlign='center';ctx.fillText('FINISH',512,92);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;mesh(new THREE.PlaneGeometry(38,4.75),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}),g,0,10.3,0);decor.push({g,z:2400});}
function makeParticles(){const count=420;particlePositions=new Float32Array(count*3);particleColors=new Float32Array(count*3);for(let i=0;i<count;i++){particleData.push({life:0,x:0,y:0,z:0,vx:0,vy:0,vz:0});particlePositions[i*3+1]=-100;}particleGeo=new THREE.BufferGeometry();particleGeo.setAttribute('position',new THREE.BufferAttribute(particlePositions,3));particleGeo.setAttribute('color',new THREE.BufferAttribute(particleColors,3));const c=document.createElement('canvas');c.width=c.height=32;const a=c.getContext('2d'),grad=a.createRadialGradient(16,16,0,16,16,16);grad.addColorStop(0,'rgba(255,255,255,1)');grad.addColorStop(.3,'rgba(255,255,255,.85)');grad.addColorStop(1,'rgba(255,255,255,0)');a.fillStyle=grad;a.fillRect(0,0,32,32);particles=new THREE.Points(particleGeo,new THREE.PointsMaterial({map:new THREE.CanvasTexture(c),size:.3,vertexColors:true,transparent:true,opacity:.8,depthWrite:false,blending:THREE.AdditiveBlending}));particles.frustumCulled=false;particles.renderOrder=3;scene.add(particles);}
function spray(n=3,burst=false){const p=disc.position;for(let i=0;i<n;i++){const id=particleCursor++%particleData.length,d=particleData[id],k=particleCursor;d.life=.4+seed(k)*.6;d.x=p.x+(seed(k+4)-.5)*2;d.y=p.y;d.z=p.z+.6;d.vx=(seed(k+1)-.5)*(burst?12:6);d.vy=state.mode==='dive'?3:2+seed(k+2)*(burst?9:3);d.vz=5+seed(k+3)*8;particleColors[id*3]=.65;particleColors[id*3+1]=.93;particleColors[id*3+2]=1;}}
function updateParticles(dt){for(let i=0;i<particleData.length;i++){const p=particleData[i];if(p.life>0){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vy-=dt*11;particlePositions[i*3]=p.x;particlePositions[i*3+1]=p.y;particlePositions[i*3+2]=p.z;if(p.life<=0)particlePositions[i*3+1]=-100;} }particleGeo.attributes.position.needsUpdate=true;particleGeo.attributes.color.needsUpdate=true;}
function init(){try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){$('loadError').hidden=false;console.error(e);return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.17;
 scene=new THREE.Scene();scene.background=new THREE.Color(0xafd4d5);scene.fog=new THREE.FogExp2(0xafd4d5,.0038);
 camera=new THREE.PerspectiveCamera(65,16/9,.15,650);
 scene.add(new THREE.HemisphereLight(0xd2f1ff,0x315340,2.15));const sun=new THREE.DirectionalLight(0xffe4ad,3.1);sun.position.set(-65,100,-80);scene.add(sun);
 // Warm solar disc above the canyon horizon, rendered in world space.
 const sunMesh=new THREE.Mesh(new THREE.SphereGeometry(13,24,16),new THREE.MeshBasicMaterial({color:0xfff5d3,fog:false}));sunMesh.position.set(-190,260,-700);scene.add(sunMesh);
 buildEnvironment();disc=makeDisc(colors.lime,true);disc.scale.setScalar(1.5);makeParticles();for(let i=0;i<7;i++){const model=makeDisc(racerColors[i]);model.scale.setScalar(.78);rivals.push(model);}
 resize();new ResizeObserver(resize).observe(game);camera.position.copy(point(-5,8, -12));disc.position.copy(point(5,.5,0));sceneReady=true;$('start').disabled=false;$('start').querySelector('span').textContent='RACE THE RIVER';requestAnimationFrame(frame);
}
function resize(){if(!renderer)return;renderer.setSize(game.clientWidth,game.clientHeight,false);camera.aspect=game.clientWidth/game.clientHeight;camera.updateProjectionMatrix();}
function command(type){if(state.phase!=='racing')return;if(validateAction(state,playerId,{type}).ok){state=applyAction(state,playerId,{type});reactEvent();}}
function reactEvent(){if(state.eventSerial===eventSeen)return;eventSeen=state.eventSerial;const e=state.event;audio.event(e);if(['jump','land','dive','surface','hit','waterfall'].includes(e))spray(e==='land'?60:35,true);const labels={boost:'PERFECT LINE  ·  BOOST',cut:'CLEAN CUT  ·  BOOST',waterfall:'FEARLESS  ·  BOOST',hit:'KEEP YOUR FLOW',route:state.route===-1?'WATERFALL  ·  FAST CURRENT':state.route===1?'CAVE  ·  STAY SHARP':'MAIN RIVER  ·  STAY SMOOTH'};if(labels[e]){if(['boost','cut','waterfall'].includes(e))boostFlash=1;feedback(labels[e],e==='hit'?'#ffba91':undefined);}if(e==='finish')finish();}
function feedback(text,color){$('feedback').textContent=text;$('feedback').style.color=color||'var(--lime)';$('feedback').classList.add('show');feedbackUntil=clock+1.4;}
function timer(t){const m=Math.floor(t/60),s=Math.floor(t%60),c=Math.floor(t*100)%100;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(c).padStart(2,'0')}`;}
function raceZ(i){return racerOffsets[i]+state.t*racerRates[i]+Math.sin(state.t*.38+i)*2;}
function updateHUD(){
 $('timer').textContent=timer(state.t);$('speed').textContent=Math.round(state.speed*3.6);$('progressFill').style.width=`${state.z/24}%`;
 const stage=state.z<90?'START':state.z<330?'RAPIDS':state.z<650?'THREE WAYS DOWN':state.z<1000?'THE GAUNTLET':state.z<1320?'THE LOST CANYON':state.z<1580?'BENEATH THE SURFACE':state.z<1920?'THE FINAL CHOICE':state.z<2400?'FINAL SPRINT':'FINISH';$('progressLabel').textContent=stage;
 const standings=racerNames.map((name,i)=>({name,z:raceZ(i),color:'#'+racerColors[i].toString(16)}));standings.push({name:'You',z:state.z,color:'#c3f542'});standings.sort((a,b)=>b.z-a.z);rank=standings.findIndex(p=>p.name==='You')+1;$('position').textContent=rank;
 $('racers').innerHTML=standings.map((p,i)=>`<div class="racer ${p.name==='You'?'you':''}"><b>${i+1}</b><i class="pip" style="--racer:${p.color}"></i><span>${p.name}</span></div>`).join('');
 const path=$('mapPath'),p=path.getPointAtLength(path.getTotalLength()*state.z/2400);$('mapDot').setAttribute('cx',p.x);$('mapDot').setAttribute('cy',p.y);
 const strength=state.boost>0?6:Math.max(0,Math.floor((state.speed-25)/6));document.querySelectorAll('.boost-bars i').forEach((v,i)=>v.classList.toggle('lit',i<strength));$('boostText').textContent=state.boost>0?'BOOST ACTIVE':state.hitT>0?'FIND YOUR FLOW':'FLOW STATE';
 for(const type of ['jump','dive','spin']){$(type).classList.toggle('cooldown',state[type+'CD']>0);$(type).classList.toggle('active',type==='spin'?state.spin>0:state.mode===type);}
 const upcoming=state.forks.find(f=>state.z>f.start-125&&state.z<f.start+15);$('routeHUD').hidden=!upcoming||state.phase!=='racing';if(upcoming){const r=state.x<-5?-1:state.x>5?1:0;document.querySelectorAll('[data-route]').forEach(el=>el.classList.toggle('selected',+el.dataset.route===r));}
 const hazard=state.obstacles.find(o=>o.z>state.z+7&&o.z<state.z+72&&Math.abs(o.x-state.x)<o.w+1&&!['ring','underrock'].includes(o.type));const hints={log:'↑  LOG AHEAD · JUMP',rock:'↔  ROCKS · STEER',bridge:'↓  LOW BRIDGE · DIVE',vine:'↻  VINES · SPIN',whirl:'↔  WHIRLPOOL · DODGE',drop:'↑  WATERFALL · JUMP'};$('hazardHint').innerHTML=hazard&&state.phase==='racing'&&!upcoming?`<span>${hints[hazard.type]}</span>`:'';
}
function frame(now){requestAnimationFrame(frame);const start=performance.now();const dt=Math.min((now-(last||now))/1000,.05);last=now;clock+=dt;
 if(state.phase==='racing'){
  const kb=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0);const input=steer||kb;acc+=dt;
  while(acc>=1/60){state=applyAction(state,playerId,{type:'tick',steer:input});acc-=1/60;reactEvent();if(state.phase!=='racing')break;}
  if(frameCounter%2===0)spray(state.boost>0?6:3);
 }else acc=0;
 const ready=state.phase==='ready';const visualX=ready?5:state.x;const visualZ=state.z;const base=level(visualZ,visualX);disc.position.set(center(visualZ)+visualX,base+state.y+Math.sin(clock*6)*.04,-visualZ);disc.rotation.z+=( -state.vx*.025-disc.rotation.z)*.12;disc.rotation.x=state.mode==='jump'?Math.sin((1-state.modeT/.95)*Math.PI)*.2:0;disc.rotation.y+=dt*(state.spin>0?35:state.boost>0?6:2.3);
 const camX=center(visualZ)+(ready?-4:state.x*.48);let camY=base+(state.mode==='dive'?-1.3:7.2)+(state.mode==='jump'?state.y*.24:0);camTarget.set(camX,camY,-visualZ+13);camera.position.lerp(camTarget,1-Math.exp(-dt*7));const shake=(!reduced&&state.hitT>0)?Math.sin(clock*70)*state.hitT*.12:0;camera.position.x+=shake;look.set(center(visualZ+26)+visualX*.48,base+(ready?2:1),-visualZ-23);if(state.mode==='dive')look.y=base-1.7;camera.lookAt(look);const fov=ready?62:65+(state.speed-46)*.32;camera.fov+=(fov-camera.fov)*.04;camera.updateProjectionMatrix();
 waterMat.uniforms.time.value=clock;waterMat.uniforms.player.value.copy(disc.position);waterMat.uniforms.dive.value+=( (state.mode==='dive'?1:0)-waterMat.uniforms.dive.value)*.2;waterMat.uniforms.speed.value=state.speed;mats.fall.uniforms.time.value=clock;
 $('underwater').style.opacity=state.mode==='dive'?'.9':'0';$('impact').style.opacity=state.hitT>.45?'.8':'0';scene.fog.density=state.mode==='dive'?.018:.0048;scene.fog.color.set(state.mode==='dive'?0x087d8a:0xafd4d5);scene.background.copy(scene.fog.color);
 for(const v of obstacleViews){v.g.visible=v.o.z>state.z-25&&v.o.z<state.z+420&&!((v.o.type==='ring'||v.o.type==='vine')&&state.cleared.includes(v.o.id));if(v.o.type==='whirl')v.visual.material.uniforms.time.value=clock;}
 for(const f of falls)f.mesh.visible=f.z>state.z-20&&f.z<state.z+340;
 for(const batch of terrainBatches)batch.mesh.visible=batch.z+180>state.z-70&&batch.z<state.z+400;
 for(let i=0;i<7;i++){const z=ready?18+i*12:raceZ(i);const x=Math.sin(z*.02+i*3)*10;rivals[i].visible=z>state.z-10&&z<state.z+160;rivals[i].position.copy(point(x,.52,z));rivals[i].rotation.y=clock*3+i;rivals[i].rotation.z=Math.sin(clock+i)*.1;}
 for(const r of rings)if(r.mesh.visible)r.mesh.rotation.z=Math.sin(clock*2)*.08;
 updateParticles(dt);if(clock>feedbackUntil)$('feedback').classList.remove('show');if(frameCounter%6===0)updateHUD();boostFlash=Math.max(0,boostFlash-dt*2);
 if(!counting)audio.update(state);renderer.render(scene,camera);cpuMs=performance.now()-start;frameCounter++;frameSample+=dt;if(frameSample>=1){fps=Math.round(frameCounter/frameSample);frameCounter=0;frameSample=0;}
 if(!$('dev').hidden)$('dev').textContent=`${fps} FPS | ${renderer.info.render.calls} calls | CPU ${cpuMs.toFixed(1)}ms | GPU not measured | ${renderer.info.render.triangles} triangles`;
}
async function startRace(){if(counting||!sceneReady)return;audio.unlock();audio.restart();$('audioPanel').hidden=true;counting=true;state=setup([playerId]);eventSeen=0;game.className='playing';$('finishPanel').hidden=true;$('pausePanel').hidden=true;keys={};steer=0;updateHUD();for(const text of ['3','2','1']){$('countdown').textContent=text;await new Promise(r=>setTimeout(r,550));}state=applyAction(state,playerId,{type:'start'});audio.setPhase('racing');$('countdown').textContent='GO';setTimeout(()=>$('countdown').textContent='',450);counting=false;startedAt=performance.now();}
function finish(){audio.setPhase('finished');game.className='finished';updateHUD();$('finishTime').textContent=timer(state.finishTime);$('finishRank').textContent=`${rank}/8`;$('finishRings').textContent=state.rings;$('finishHits').textContent=state.hits;let best=0;try{best=Number(localStorage.getItem('freshbee-best')||0);if(!best||state.finishTime<best)localStorage.setItem('freshbee-best',String(state.finishTime));}catch{}$('best').textContent=!best||state.finishTime<best?'NEW PERSONAL BEST':`PERSONAL BEST  ${timer(best)}`;$('finishPanel').hidden=false;$('routeHUD').hidden=true;}
function pause(){if(state.phase==='racing'){state=applyAction(state,playerId,{type:'pause'});audio.setPhase('paused');$('pausePanel').hidden=false;keys={};steer=0;}else if(state.phase==='paused'){audio.unlock();state=applyAction(state,playerId,{type:'resume'});audio.setPhase('racing');$('pausePanel').hidden=true;}}
$('start').onclick=startRace;$('replay').onclick=startRace;$('restartPause').onclick=startRace;$('pause').onclick=pause;$('resume').onclick=pause;$('motion').onchange=e=>reduced=e.target.checked;
$('fullscreen').onclick=async()=>{try{if(!document.fullscreenElement)await game.requestFullscreen();else await document.exitFullscreen();if(screen.orientation?.lock)await screen.orientation.lock('landscape').catch(()=>{});}catch{}};
function toggleSound(){audio.unlock();audio.toggleMute();}
$('sound').onclick=toggleSound;
$('mixer').onclick=()=>{const open=$('audioPanel').hidden;$('audioPanel').hidden=!open;$('mixer').setAttribute('aria-expanded',String(open));};
$('closeAudio').onclick=()=>{$('audioPanel').hidden=true;$('mixer').setAttribute('aria-expanded','false');};
for(const [channel,id,valueId] of [['music','musicVolume','musicValue'],['effects','effectsVolume','effectsValue']]){const input=$(id);input.value=Math.round(audio.settings[channel]*100);$(valueId).textContent=input.value+'%';input.addEventListener('input',()=>{audio.unlock();audio.setVolume(channel,Number(input.value)/100);$(valueId).textContent=input.value+'%';});}
window.addEventListener('keydown',e=>{if(e.code==='KeyM'&&!e.repeat&&!['INPUT','TEXTAREA'].includes(e.target?.tagName))toggleSound();});
audio.emit();
$('quality').onclick=()=>{hq=!hq;renderer.setPixelRatio(hq?Math.min(devicePixelRatio,1.25):.8);resize();$('quality').textContent=hq?'HQ':'LITE';};
for(const type of ['jump','dive','spin'])$(type).addEventListener('pointerdown',e=>{e.preventDefault();command(type);});
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target?.tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.repeat)return;const map={KeyW:'jump',ArrowUp:'jump',KeyS:'dive',ArrowDown:'dive',Space:'spin'};if(map[e.code])command(map[e.code]);if(e.code==='Escape'||e.code==='KeyP')pause();if(e.code==='Enter'&&state.phase==='ready')startRace();if(e.code==='KeyR'&&state.phase==='finished')startRace();});window.addEventListener('keyup',e=>keys[e.code]=false);
window.addEventListener('blur',()=>{keys={};steer=0;if(state.phase==='racing')pause();});document.addEventListener('visibilitychange',()=>{audio.setHidden(document.hidden);if(document.hidden&&state.phase==='racing')pause();});
let pointer=null;const joy=$('joystick');function moveStick(e){const rect=joy.querySelector('.joystick-ring').getBoundingClientRect();const dx=e.clientX-rect.left-rect.width/2;steer=clamp(dx/(rect.width*.35),-1,1);$('stick').style.transform=`translateX(${steer*rect.width*.26}px)`;joy.setAttribute('aria-valuenow',steer.toFixed(2));}
joy.addEventListener('pointerdown',e=>{e.preventDefault();pointer=e.pointerId;joy.setPointerCapture(pointer);moveStick(e);});joy.addEventListener('pointermove',e=>{if(e.pointerId===pointer)moveStick(e);});function release(e){if(pointer===e.pointerId){pointer=null;steer=0;$('stick').style.transform='';joy.setAttribute('aria-valuenow','0');}}joy.addEventListener('pointerup',release);joy.addEventListener('pointercancel',release);joy.addEventListener('lostpointercapture',release);
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();if(state.phase==='racing')pause();$('loadError').hidden=false;});
window.freshbee={getAudio:()=>audio.debug(),getState:()=>structuredClone(state),getStats:()=>({fps,calls:renderer?.info.render.calls,cpuMs,triangles:renderer?.info.render.triangles,webgl:!!renderer}),command,start:startRace,step:(n=1,input=0)=>{for(let i=0;i<n;i++){state=applyAction(state,playerId,{type:'tick',steer:input});reactEvent();}return state;},setState:patch=>{state={...state,...patch};},pause};
if(new URLSearchParams(location.search).has('debug'))$('dev').hidden=false;
init();
